### ISSUE TITLE
Empty labels

### ISSUE THREAD

**Issue by BartoszMilewski** [wetneb/sheetshow#15]
Shouldn't this produce a single wire?
```
inputs:
- []
outputs:
- []
```

**Comment by wetneb** [comment]
No I think the current rendering (a single empty blue sheet) is correct: you are specifying a single sheet (with your single bullet point) which has no wires on it (since the list is empty). So this morphism is indeed the identity on the multiplicative unit.

To get a single wire you could do:
```
inputs:
- 1
outputs:
- 1
```
https://wetneb.github.io/sheetshow/#eyJpbnB1dHMiOlsxXSwic2xpY2VzIjpbXSwib3V0cHV0cyI6WzFdfQ==
